export const GET_CRYPTO_REQUEST = "GET_CRYPTO_REQUEST";
export const GET_CRYPTO_SUCCESS = "GET_CRYPTO_SUCCESS";
export const GET_CRYPTO_FAIL = "GET_CRYPTO_FAIL";

export const GET_TARGET_REQUEST = "GET_TARGET_REQUEST";
export const GET_TARGET_SUCCESS = "GET_TARGET_SUCCESS";
export const GET_TARGET_FAIL = "GET_TARGET_FAIL";

export const UPDATE_CRYPTO_TARGET_REQUEST = "UPDATE_CRYPTO_TARGET_REQUEST";
export const UPDATE_CRYPTO_TARGET_SUCCESS = "UPDATE_CRYPTO_TARGET_SUCCESS";
export const UPDATE_CRYPTO_TARGET_FAIL = "UPDATE_CRYPTO_TARGET_FAIL";
